### ISSUE TITLE
cannot check out on windows

### ISSUE THREAD

**Issue by Eh2406** [anp/lolbench-analysis#1]
Hi, This repo can not be checked out on windows as it has `::` in folder names, which windows does not except.

I get that this repo is a [temporary solution](https://github.com/anp/lolbench/issues/4) so this issue may not be worth fixing.

For now I will use the `allresults-Mean.json` file. Thanks for having it!

**Comment by anp** [comment]
https://github.com/anp/lolbench-data is where the automatic upload is happening -- the storage format is optimized for the runners, but all the code to retrieve available results is in the lolbench repo. Let me know if you try that and run into problems!
